/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcercaRouteImport } from './routes/acerca'
import { Route as AnimacionRouteImport } from './routes/animacion'
import { Route as ConceptRouteImport } from './routes/concept'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ModeladoRouteImport } from './routes/modelado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaRoute = AcercaRouteImport.update({
  id: '/acerca',
  path: '/acerca',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimacionRoute = AnimacionRouteImport.update({
  id: '/animacion',
  path: '/animacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptRoute = ConceptRouteImport.update({
  id: '/concept',
  path: '/concept',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeladoRoute = ModeladoRouteImport.update({
  id: '/modelado',
  path: '/modelado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/animacion': typeof AnimacionRoute
  '/concept': typeof ConceptRoute
  '/contacto': typeof ContactoRoute
  '/modelado': typeof ModeladoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/animacion': typeof AnimacionRoute
  '/concept': typeof ConceptRoute
  '/contacto': typeof ContactoRoute
  '/modelado': typeof ModeladoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/animacion': typeof AnimacionRoute
  '/concept': typeof ConceptRoute
  '/contacto': typeof ContactoRoute
  '/modelado': typeof ModeladoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/acerca' | '/animacion' | '/concept' | '/contacto' | '/modelado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acerca' | '/animacion' | '/concept' | '/contacto' | '/modelado'
  id:
    | '__root__'
    | '/'
    | '/acerca'
    | '/animacion'
    | '/concept'
    | '/contacto'
    | '/modelado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaRoute: typeof AcercaRoute
  AnimacionRoute: typeof AnimacionRoute
  ConceptRoute: typeof ConceptRoute
  ContactoRoute: typeof ContactoRoute
  ModeladoRoute: typeof ModeladoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca': {
      id: '/acerca'
      path: '/acerca'
      fullPath: '/acerca'
      preLoaderRoute: typeof AcercaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animacion': {
      id: '/animacion'
      path: '/animacion'
      fullPath: '/animacion'
      preLoaderRoute: typeof AnimacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept': {
      id: '/concept'
      path: '/concept'
      fullPath: '/concept'
      preLoaderRoute: typeof ConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelado': {
      id: '/modelado'
      path: '/modelado'
      fullPath: '/modelado'
      preLoaderRoute: typeof ModeladoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaRoute: AcercaRoute,
  AnimacionRoute: AnimacionRoute,
  ConceptRoute: ConceptRoute,
  ContactoRoute: ContactoRoute,
  ModeladoRoute: ModeladoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
